sudo: false

language: go

go:
  - 1.10.3

# Only clone the most recent commit
git:
  depth: 1

env:
  global:
    - DEP_VERSION="0.5.0"
    - GOLANGCI_LINT_VERSION="1.9.3"

before_install:
  # Download dep binary to $GOPATH/bin
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  # Download golangci-lint binary to $GOPATH/bin
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v${GOLANGCI_LINT_VERSION}

install:
  - dep ensure

script:
  - golangci-lint run -v
      -E golint
      -E interfacer
      -E unconvert
      -E dupl
      -E goconst
      -E gocyclo
      -E maligned
      -E misspell
      -E lll
      -E unparam
      consumer/...
      mocks/...
      producer/...
  - go test -v ./...
